/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include "tcMenuU8g2.h"
#include <IoAbstraction.h>
#include <EepromItemStorage.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern U8G2_SSD1306_128X64_NONAME_F_SW_I2C gfx;
extern U8g2Drawable gfxDrawable;
extern GraphicsDeviceRenderer renderer;

// Any externals needed by IO expanders, EEPROMs etc


// Global Menu Item exports
extern BackMenuItem menuBackPowerMode;
extern SubMenuItem menuPowerMode;
extern BackMenuItem menuBackEncoderSensitivity;
extern SubMenuItem menuEncoderSensitivity;
extern BackMenuItem menuBackDisplaySettings;
extern SubMenuItem menuDisplaySettings;
extern BackMenuItem menuBackGeneralSettings;
extern SubMenuItem menuGeneralSettings;
extern BackMenuItem menuBackPreviousErrorLog;
extern SubMenuItem menuPreviousErrorLog;
extern BackMenuItem menuBackCurrentError;
extern SubMenuItem menuCurrentError;
extern BackMenuItem menuBackErrorLog;
extern SubMenuItem menuErrorLog;
extern BackMenuItem menuBackParameterGraphing;
extern SubMenuItem menuParameterGraphing;
extern BackMenuItem menuBackTemperatureValues;
extern SubMenuItem menuTemperatureValues;
extern BackMenuItem menuBackPressureValues;
extern SubMenuItem menuPressureValues;
extern BackMenuItem menuBackSensorValues;
extern SubMenuItem menuSensorValues;
extern BackMenuItem menuBackPressure;
extern SubMenuItem menuPressure;
extern BackMenuItem menuBackTemperature;
extern SubMenuItem menuTemperature;
extern BackMenuItem menuBackCustomCalibrate;
extern SubMenuItem menuCustomCalibrate;
extern BackMenuItem menuBackNewSubMenu;
extern SubMenuItem menuNewSubMenu;
extern BackMenuItem menuBackHardOperation;
extern SubMenuItem menuHardOperation;
extern BackMenuItem menuBackMediumOperation;
extern SubMenuItem menuMediumOperation;
extern BackMenuItem menuBackTemperatureRange;
extern SubMenuItem menuTemperatureRange;
extern BackMenuItem menuBackPressureRange;
extern SubMenuItem menuPressureRange;
extern BackMenuItem menuBackDocumentation;
extern SubMenuItem menuDocumentation;
extern BackMenuItem menuBackSoftOperation;
extern SubMenuItem menuSoftOperation;
extern BackMenuItem menuBackOperationMode;
extern SubMenuItem menuOperationMode;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuOperationMode; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION CurrentError(int id);
void CALLBACK_FUNCTION ErrorLog(int id);
void CALLBACK_FUNCTION Log_ReadMe(int id);
void CALLBACK_FUNCTION PressureData(int id);
void CALLBACK_FUNCTION PressureValues(int id);
void CALLBACK_FUNCTION SoftModeFunction(int id);
void CALLBACK_FUNCTION Temperature(int id);

#endif // MENU_GENERATED_CODE_H
